name: Terraform CI/CD

on:
  push:
    branches:
      - main
      - destroy
permissions:
  contents: read
  id-token: write

## falta configurar el tema del apply
jobs:
  apply:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4


      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::859551916894:role/terraform-pipelines
          aws-region: us-east-2
          role-session-name: tf-gha-plan

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Terraform Init
        run: terraform -chdir=infra/modules init -input=false

      - name: Terraform Plan
        run: terraform -chdir=infra/modules plan -out=tfplan

      - name: Terraform Apply
        run: terraform -chdir=infra/modules apply -auto-approve tfplan


## falta configurar el tema del destroy
  destroy:
    if: github.ref == 'refs/heads/destroy'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4


      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::859551916894:role/terraform-pipelines
          aws-region: us-east-2
          role-session-name: tf-gha-apply

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Terraform Init (same backend)
        run: terraform -chdir=infra/modules init -input=false

      - name: Terraform destroy
        run: terraform -chdir=infra/modules destroy -auto-approve tfplan
